spring.application.name=client

spring.datasource.url=jdbc:postgresql://dpg-cpsgsk08fa8c739m1a50-a.oregon-postgres.render.com/credito_card_db?sslmode=require
spring.datasource.username=credito_card_user
spring.datasource.password=g92nQnN2R3Q1z2wreX6YhZqA8k696zPj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}