spring.application.name=client

# 1. Base de Datos - USAMOS LA URL EXTERNA CON SSL MANDATORIO
spring.datasource.url=jdbc:postgresql://dpg-cpsgsk08fa8c739m1a50-a.oregon-postgres.render.com/credito_card_db?sslmode=require
spring.datasource.username=credito_card_user
spring.datasource.password=g92nQnN2R3Q1z2wreX6YhZqA8k696zPj

# 2. Configuraciones de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true

# 3. Solución para el puerto en Render
server.port=${PORT:8080}